#!/bin/bash

# >&2 is equivalent to 1>&2
[[ $# -ne 1 ]] && { echo "Need one argument" >&2; exit 1; }

word="$1"

case $word in
	cat|kitten) 
		echo "meow"
		;;
	dog|puppy|pup)
		echo "bow bow"
		;;
	cow|calf)
		echo "moo moo"
		;;
	*)
		echo "not an animal"
		;;
esac

exit 0