#!/bin/bash

# get the date
date=$(date)

# get the topic
topic="$1"

filename="${HOME}/${topic}notes.txt"

read -p "Enter note:" note


if [[ $note ]]; then
  echo "$date: $note" >> "$filename"
  echo "Added 'note' to $filename"
else
  echo "No input from the user"
fi



