#!/bin/bash

# get the date
declare -r date=$(date)

# get the topic
declare -r topic="$1"

filename="${HOME}/${topic}notes.txt"

read -p "Enter note:" note


if [[ $note ]]; then
  echo "$date: $note" >> "$filename"
  echo "Added 'note' to $filename"
else
  echo "No input from the user" 1>&2
fi



